### ISSUE TITLE
Broken endpoint for newly registered users

### ISSUE THREAD

**Issue by ghost** [codebuddies/cb-connect#79]
When a user finished inputting their information and hits submit, the endpoint hangs up.

The meteor console reads:

```
I20190506-14:40:07.608(-6)? { Error: Invalid login: 535 5.7.8 Sorry.
I20190506-14:40:07.612(-6)?     at SMTPConnection._formatError (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:558:19)
I20190506-14:40:07.615(-6)?     at SMTPConnection._actionAUTHComplete (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:1254:34)
I20190506-14:40:07.616(-6)?     at SMTPConnection._responseActions.push.str (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:341:26)
I20190506-14:40:07.616(-6)?     at SMTPConnection._processResponse (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:707:20) I20190506-14:40:07.617(-6)?     at SMTPConnection._onData (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:510:14)
I20190506-14:40:07.617(-6)?     at TLSSocket._socket.on.chunk (C:\Users\chris\AppData\Local\.meteor\packages\email\1.2.3\npm\node_modules\node4mailer\lib\smtp-connection\index.js:658:51)
I20190506-14:40:07.618(-6)?     at emitOne (events.js:116:13)
I20190506-14:40:07.618(-6)?     at TLSSocket.emit (events.js:211:7)
I20190506-14:40:07.619(-6)?     at addChunk (_stream_readable.js:263:12)
I20190506-14:40:07.619(-6)?     at readableAddChunk (_stream_readable.js:250:11)
I20190506-14:40:07.620(-6)?     at TLSSocket.Readable.push (_stream_readable.js:208:10)
I20190506-14:40:07.620(-6)?     at TLSWrap.onread (net.js:597:20)
I20190506-14:40:07.621(-6)?   code: 'EAUTH',
I20190506-14:40:07.621(-6)?   response: '535 5.7.8 Sorry.',
I20190506-14:40:07.622(-6)?   responseCode: 535,
I20190506-14:40:07.622(-6)?   command: 'AUTH PLAIN' }
```

If the in-browser console is read, you can see some sockJs errors such as 

```
The connection to ws://localhost:3000/sockjs/663/ushrz9bh/websocket was interrupted while the page was loading.
```

**Comment by angelocordon** [comment]
Thanks, @mcsmithers - I think this is a known issue - the endpoint _does_ hang up when you don't have a valid Sparkpost API key defined. I'm planning on reworking our registration flow to mitigate this but still need to explore which bits and pieces need to be worked on. 

For what it's worth, in a local environment, the registration form does create an entry in the database, it exists, the UI just hangs when the platform can't properly send an email. In the local environment, the default password is `password` if you're trying to sign in.
